spring.application.name=bis
spring.datasource.url=jdbc:postgresql://localhost:5432/book_illustration_studio
spring.datasource.username=bookstudio
spring.datasource.password=bookstudio
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect